log_files: fix chunks_received size in download_log_file
mavlink/MAVSDK pull request #1180
Opened 2020-08-27 12:24 UTC by NicolasM0

I have always an error at the end of downloading a log file :
![Sans titre](https://user-images.githubusercontent.com/59083163/91441482-93179980-e870-11ea-821a-0b0cd748edff.png)

I use a mavsdk_server compiled on develop branch on Windows.

After digging a bit, I found that if log part size in not a multiple of MAVLINK_MSG_LOG_DATA_FIELD_DATA_LEN 
(it seems that there is no reason to be of a particular size),
chunks_received size must be "part_size / MAVLINK_MSG_LOG_DATA_FIELD_DATA_LEN +1"

2020-08-27 12:40 UTC, JonasVautherin reviewed
Interesting... Why could that be? Some null termination `\0`?

2020-08-27 14:26 UTC, julianoes approved these changes
I think that makes sense. Nice catch @NicolasM0.

2020-08-27 20:54 UTC, JonasVautherin requested changes
Please update the branch (rebase `develop`) and fix the style (`./tools/fix_style.sh .`). Then it will be good to go :+1: :rocket:

2020-08-28 07:13 UTC, NicolasM0 commented
> Please update the branch (rebase `develop`) and fix the style (`./tools/fix_style.sh .`). Then it will be good to go 👍 🚀

done !

2020-08-28 09:38 UTC, JonasVautherin approved these changes
Awesome! Thanks!

2020-08-28 09:38 UTC, merged