Add GetAllParams function
mavlink/MAVSDK pull request #1191
Opened 2020-09-18 20:20 UTC by helo9

This PRs aim to introduce a GetAllParams function, as already started in [MAVSDK-Proto PR#175](https://github.com/mavlink/MAVSDK-Proto/pull/175). 
The only testing I have done so far is the integration test I have added. Therefore I keep it a draft for now.

2020-09-21 11:53 UTC, JonasVautherin requested changes
Seems good to me! The docs CI test is failing, with:

```
Compound mavsdk::Param::IntParam is not documented.
Compound mavsdk::Param::AllParams is not documented.
Compound mavsdk::Param::FloatParam is not documented.
```

I think that's because the `messages` miss the documentation [here](https://github.com/mavlink/MAVSDK-Proto/blob/32a60e437e84daf1ec440504c374e7cd46256592/protos/param/param.proto#L80-L81), [here](https://github.com/mavlink/MAVSDK-Proto/blob/32a60e437e84daf1ec440504c374e7cd46256592/protos/param/param.proto#L85-L86) and [here](https://github.com/mavlink/MAVSDK-Proto/blob/32a60e437e84daf1ec440504c374e7cd46256592/protos/param/param.proto#L90-L91)

2020-09-21 11:53 UTC, JonasVautherin commented on src/plugins/param/param_impl.cpp
> +        }*/
```suggestion
        }
```

2020-09-30 21:09 UTC, JonasVautherin approved these changes
Thanks a lot!

2020-09-30 22:40 UTC, merged

2020-10-01 06:15 UTC, helo9 commented
> Thanks a lot!

Thank you for updating the protos :+1: