exmaples: Add gimbal device tester (WIP)
mavlink/MAVSDK pull request #1206
Opened 2020-10-06 14:31 UTC by julianoes

This is work in progress to test a gimbal device according to the gimbal v2 protocol, see: https://mavlink.io/en/services/gimbal_v2.html#how-to-implement-the-gimbal-device-interface

2020-10-07 17:37 UTC, MatejFranceskin approved these changes
Looks good to me.

2020-10-07 17:37 UTC, MatejFranceskin commented on examples/gimbal_device_tester/gimbal_device_tester.cpp
> +static  void send_gimbal_device_set_attitude(MavlinkPassthrough& mavlink_passthrough);
2 spaces between static  void...
(At least I found something ;-)

2020-10-16 15:04 UTC, julianoes commented
Let's merge this asap and then iterate on it.

2020-10-16 16:40 UTC, JonasVautherin requested changes

2020-10-16 16:40 UTC, JonasVautherin commented on examples/gimbal_device_tester/gimbal_device_tester.cpp
> +    System& system = mavsdk.system();
This is deprecated, I think that's why the CI complains

2020-10-16 17:32 UTC, merged