Distance sensor 2
mavlink/MAVSDK pull request #1222
Opened 2020-10-09 09:40 UTC by hrnbot

2020-10-12 07:45 UTC, julianoes requested changes

2020-10-12 07:45 UTC, julianoes commented on .idea/workspace.xml
> +</project>
Please remove this file from the pull request as it is unrelated.

2020-10-12 07:45 UTC, julianoes commented on src/plugins/telemetry/telemetry_impl.h
> +    // The velocity (former ground speed) and position are coupled to the same message, therefore,
```suggestion
```

2020-10-12 08:45 UTC, julianoes requested changes

2020-10-12 08:45 UTC, julianoes commented on src/plugins/telemetry/include/plugins/telemetry/telemetry.h
> +        float min_distance{}; /**< @brief Minimum distance the sensor can measure. */
I don't think this is up-to-date. I don't see the `_m` yet.

2020-10-12 11:27 UTC, JonasVautherin requested changes
Please don't push `.idea/` :blush:. The rest seems fine :+1:.

2020-10-12 12:16 UTC, JonasVautherin approved these changes

2020-10-13 09:07 UTC, julianoes approved these changes
Looks all good now!

2020-10-13 12:38 UTC, merged