telemetry: add gimbal v2 attitude status
mavlink/MAVSDK pull request #1233
Opened 2020-10-21 11:19 UTC by julianoes

This enable the attitude feedback for the gimbal v2 MAVLink protocol.

2020-10-21 14:33 UTC, JonasVautherin requested changes

2020-10-21 14:33 UTC, JonasVautherin commented on src/plugins/mission/mission_impl.cpp
> +    // mavlink_msg_gimbal_manager_information_decode(&message, &gimbal_manager_information);
```suggestion
```

2020-10-22 05:50 UTC, julianoes commented on src/plugins/mission/mission_impl.cpp
> +    // mavlink_msg_gimbal_manager_information_decode(&message, &gimbal_manager_information);
Yer, you're right.

2020-10-22 06:20 UTC, julianoes commented
@JonasVautherin thanks for the review. I'm just waiting for https://github.com/mavlink/MAVSDK-Proto/pull/184 before pushing here again.

2020-10-23 08:04 UTC, JonasVautherin approved these changes
LGTM

2020-10-23 08:04 UTC, merged