tools: don't display command not found
mavlink/MAVSDK pull request #1408
Opened 2021-04-09 08:59 UTC by julianoes

This just caught my eye.

2021-04-09 11:07 UTC, JonasVautherin requested changes
Hmm which terminal did you test it with? For me with zsh and sh:

sh:
```
$ type podman > /dev/null
$ type podman 2> /dev/null
podman: not found
```

zsh:

```
% type podman > /dev/null
% type podman 2> /dev/null
podman not found
```

So it seems to me that `>` does what I expect, and `2>` does not :thinking:

2021-04-09 12:08 UTC, julianoes commented
odd, I tested it in zsh.

2021-04-12 11:57 UTC, julianoes commented
```
tools/run-docker.sh tools/fix_style.sh .
tools/run-docker.sh: line 5: type: podman: not found
Starting with UID: 1000
```

2021-04-12 11:58 UTC, julianoes commented
Bash:
```
type podman > /dev/null
bash: type: podman: not found
```

2021-04-12 12:00 UTC, julianoes commented
And since this is made for bash I think the PR is correct.

2021-04-12 12:02 UTC, JonasVautherin reviewed
What about a tradeoff? Works for me on `sh`, `zsh` and `bash`.

2021-04-12 12:02 UTC, JonasVautherin commented on tools/run-docker.sh
> +if type podman 2> /dev/null
```suggestion
if type podman > /dev/null 2> /dev/null
```

2021-04-12 12:02 UTC, JonasVautherin commented on tools/run-docker.sh
> +elif type docker 2> /dev/null
```suggestion
elif type docker > /dev/null 2> /dev/null
```

2021-04-13 06:12 UTC, julianoes commented
Hm, you're right. :)

2021-04-13 09:07 UTC, merged