Add file upload callback registration for mavlink FTP server
mavlink/MAVSDK pull request #1469
Opened 2021-06-18 11:33 UTC by MatejFranceskin

This PR adds a method to register file uploaded to Mavlink FTP server callback.
When file is successfully uploaded the callback is called with the file path as parameter.

2021-06-18 22:33 UTC, JonasVautherin commented
Thanks Matej!

How is that different from `upload_async(std::string local_file_path, std::string remote_dir, UploadCallback callback);`? Doesn't the callback serve the same purpose?

2021-06-21 14:20 UTC, julianoes commented
@JonasVautherin this is for the server to be notified when something has been uploaded, so it's different, I think.

2021-06-21 14:21 UTC, julianoes requested changes

2021-06-21 14:21 UTC, julianoes commented on src/plugins/ftp/include/plugins/ftp/ftp.h
> +
This file is auto-generated from https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/ftp/ftp.proto, you can't change it like that.

2021-06-22 17:18 UTC, MatejFranceskin commented
After more testing I found some additional problems. QGC mavlink FTP client ends the upload with reset session instead of terminate and I had to find a different way to achive what I needed.
I am closing this since it is not needed anymore and it might cause problems.

2021-06-22 17:18 UTC, closed without merging