plugin: corrected support for basic actions for ardupilot
mavlink/MAVSDK pull request #1738
Opened 2022-04-14 16:49 UTC by ykhedar

At the moment, takeoff action for APM does not work at all with MAVSDK since takeoff command can only be executed with the flight mode Guided for APM. Arming works sometime but does not work after landing is completed. 

Following the work from https://github.com/mavlink/MAVSDK/pull/1703, this pull request tries to correct the broken actions (takeoff and arming) for Ardupilot. 

Following are the changes made:
1. Arming for Ardupilot(Copter 4.1.2) can be done only in specific flight modes: Hold, Stabilized and Offboard. To keep compatibility with PX4 and MAVSDK, Hold mode is selected for arming of the copter.
2. Takeoff can only be done in Offboard mode, hence a function specific to apm takeoff is implemented to take care of this.
3. Flight mode conversion between Arducopter and MAVSDK is also updated.
4. Integration tests are added/updated for mission raw and action hover. This way 7 more integration tests for APM will run now in addition to the 5 previously.

Looking forward to get reviews :)

2022-04-14 22:00 UTC, JonasVautherin requested changes
Nice! :rocket: 

A few suggestions, and I think you misspelled some `APM*` tests, I guess that's why it fails the PX4 CI checks

2022-04-16 03:54 UTC, julianoes commented
@ykhedar I really appreciate your work here. I hope to get to it soon. That being said I also have a couple of refactoring changes in a local branch related to this, that will heavily conflict. I will have to resolve the conflicts.

2022-06-06 23:01 UTC, JonasVautherin requested changes

2022-06-07 06:36 UTC, ykhedar commented on src/mavsdk/plugins/action/action_impl.cpp
> +        _parent->get_flight_mode() == FlightMode::Land) { // Needed for APM
agree with your suggestion :)

2022-06-07 06:40 UTC, ykhedar commented on src/mavsdk/core/system_impl.cpp
> +        // case FlightMode::Takeoff:
moved to unknown for now.

2022-06-07 06:41 UTC, ykhedar commented
@julianoes you mentioned before that you are working on a local branch which might conflict with this PR. Is that still the case? I did a rebase to the current main branch and resolved some conflicts thus arising.

2022-06-07 10:30 UTC, JonasVautherin approved these changes
Nice!

2022-06-20 09:27 UTC, ykhedar commented
> Is the CI failure related to this PR?

Not really. Randomly one or two of the tests fail because the `health_all_ok` is not true. I did some digging and found its mostly because the home position not received/set. I did a test locally by making the home position request to retry every 2 seconds until home position is received something like this:

`_parent->add_call_every([this]() { request_home_position_again(); }, 2.0f, &_call_every_cookie);`

The change seems to make the integration tests pass (at least for the 10 times i tested locally.)
I was thinking making that another PR since was not related to this PR. If you disagree i can commit the changes to this PR

2022-06-20 16:55 UTC, merged