Fix to allow non-flight controller heartbeats to be processed
mavlink/MAVSDK pull request #1760
Opened 2022-05-03 15:59 UTC by pweids

The change from https://github.com/mavlink/MAVSDK/pull/1752 inadvertantly threw a warning for all heartbeats that came from an "INVALID" autopilot. However, this is acceptable according to the [Heartbeat protocol.](https://mavlink.io/en/messages/common.html#HEARTBEAT) This small commit fixes that issue.

2022-05-03 19:38 UTC, JonasVautherin approved these changes

2022-05-03 21:13 UTC, bazfp commented
Looks good to me!

2022-05-03 21:18 UTC, bazfp requested changes
Actually, this reverts my changes and allows vehicle type to be changed by non autopilot heartbeats again, which makes no sense. Can you brace the vehicle change so it only happens if the autopilot sends it

2022-05-03 21:40 UTC, pweids commented
You’re right, it would. I misinterpreted the intent of your change. Thought
you just wanted to give a warning. I’ll update. And thanks for the review!

On Tue, May 3, 2022 at 5:18 PM bazfp ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Actually, this reverts my changes and allows vehicle type to be changed by
> non autopilot heartbeats again, which makes no sense. Can you brace the
> vehicle change so it only happens if the autopilot sends it
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mavlink/MAVSDK/pull/1760#pullrequestreview-961102452>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARQH2473DVC6SRO4JV3RVLVIGJ3TANCNFSM5U7K5OXQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-05-04 15:32 UTC, pweids commented
@bazfp please confirm the update fixes it

2022-05-05 13:47 UTC, pweids commented
I'm sure I'm missing something, but the logic that prints the error message is the same (heartbeat is from an autopilot and the vehicle type has changed). Furthermore, it's odd that the types are not printed out by the warnings. And it works just fine with you in the other version? How can I replicate your test?

See anything I'm missing?

2022-05-06 03:04 UTC, julianoes commented
> Is the intent of MAVSDK to only support autopilot types? Why would a system not want to receive non autopilot components heartbeats? For example, how would you connect to component 192, which is QGC's component ID with this implementation?

No, that's certainly not the intent. A `System` should represent all components, and they can all send heartbeats.

2022-05-06 06:26 UTC, julianoes commented
I will revisit this in the next days, thanks for the PR.

2022-05-09 00:27 UTC, julianoes commented
I've added two commits to prevent it from warning initially, and to fix the actual warning so it makes more sense.

@bazfp @JonasVautherin could you check if this works for you like that?

2022-05-09 00:28 UTC, julianoes approved these changes

2022-05-09 22:03 UTC, JonasVautherin approved these changes
Seems to be working fine for me, both on sim and on the bench :+1:

2022-05-09 22:45 UTC, julianoes commented
Ok, I'm going to merge it and revisit later if this doesn't work for you @bazfp.

2022-05-09 22:45 UTC, merged

2022-05-10 12:14 UTC, bazfp commented
This looks like it works for me. The intent of the original change was to stop rogue MAVLink components incorrectly setting the entire system vehicle type for MAVSDK. It was my mistake that it blocked them :)

2022-05-10 17:54 UTC, pweids commented
Thanks, everyone!

2022-06-08 14:10 UTC, bazfp reviewed
Just ran into some issues while testing this:

2022-06-19 17:35 UTC, julianoes commented
@bazfp ok what about it? :thinking: