PR Add battery proto status message for v1
mavlink/MAVSDK pull request #1939
Opened 2022-12-01 11:11 UTC by Katawann

Following the new messages in MAVSDK-Proto, it is required to implement the logic and conversion if necessary of the battery status

temperature
current_battery
current_consumed
energy_consumed

2022-12-05 16:26 UTC, Katawann commented
Hi @julianoes and @JonasVautherin 

ready for a review :) For the proto check, I guess it requires to update the proto submodule but we need to merge in MAVSDK proto first right ?

2023-01-11 12:08 UTC, JonasVautherin approved these changes
LGTM

2023-01-11 12:08 UTC, JonasVautherin commented on src/integration_tests/telemetry_async.cpp
> +              << "temparutre: " << battery.temperature_degc << " degC,"
```suggestion
              << "temperature: " << battery.temperature_degc << " degC,"
```

2023-01-11 12:08 UTC, JonasVautherin requested changes
Well actually just the typo to fix :innocent:

2023-01-11 17:50 UTC, JonasVautherin commented
Does it request an update of `mavsdk-proto`? I see the proto check fails

2023-01-11 18:05 UTC, Katawann commented
> Does it request an update of `mavsdk-proto`? I see the proto check fails

Yes but should it be merged first so than I can update it ? https://github.com/mavlink/MAVSDK-Proto/pull/297

2023-01-12 21:53 UTC, merged

2023-01-12 21:53 UTC, julianoes commented
Thanks @Katawann and sorry it took so long.

2023-01-25 21:49 UTC, Katawann commented
Any plan for a big release soon (including this feature) ? Otherwise I will build this modification on top of v1.4.10 next week

2023-01-26 01:57 UTC, julianoes commented
I'm hoping for end of Feb for v2.

2023-01-27 08:17 UTC, Katawann commented
Ok cool ! Thanks for the answer. Looking forward to it :)