Winch and Gripper plugins
mavlink/MAVSDK pull request #1958
Opened 2023-01-20 10:42 UTC by potaito

## Related PRs
- Proto: https://github.com/mavlink/MAVSDK-Proto/pull/308
- MAVSDK: 
- MAVSDK-Python:

## Description
Allows winch and gripper control via MAVSDK using the messages
- MAV_CMD_DO_GRIPPER [(211)](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_GRIPPER)
- MAV_CMD_DO_WINCH ([42600](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_WINCH) )

Winches and grippers are supposed to send out a heartbeat. I only added knowledge of the winch heartbeat to `system_impl.cpp`, since grippers don't have their own MAV_TYPE, and I think we are assuming that grippers and winches can be the same device actually. Other than that the HEARTBEAT is ignored, and only WINCH_STATUS is parsed.

Tests done:
- [x] Controlling a gripper
- [x] Controlling a winch
- [ ] Subscribing to winch status messages

2023-01-31 13:12 UTC, JonasVautherin submitted a review, later dismissed

2023-01-31 13:15 UTC, potaito commented on src/mavsdk/plugins/gripper/gripper_impl.cpp
> +    command.target_component_id = MAV_COMPONENT::MAV_COMP_ID_WINCH; // TODO
Sort of, because there is also a discussion whether grippers and winches are more or less the same thing :sweat_smile:

2023-02-01 09:50 UTC, JonasVautherin submitted a review, later dismissed

2023-02-01 11:28 UTC, JonasVautherin commented on src/mavsdk/plugins/winch/winch_impl.cpp
> +    command.params.maybe_param1 = instance;
Something like this maybe? For the -Werror in Windows

```suggestion
    command.params.maybe_param1 = static_cast<float>(instance);
```

2023-02-01 11:51 UTC, JonasVautherin commented on src/mavsdk/plugins/winch/winch_impl.cpp
> +    command.params.maybe_param1 = instance;
```suggestion
    command.params.maybe_param1 = static_cast<float>(instance);
```

2023-02-01 11:51 UTC, JonasVautherin commented on src/mavsdk/plugins/winch/winch_impl.cpp
> +    command.params.maybe_param1 = instance;
```suggestion
    command.params.maybe_param1 = static_cast<float>(instance);
```

2023-02-01 11:51 UTC, JonasVautherin commented on src/mavsdk/plugins/winch/winch_impl.cpp
> +    command.params.maybe_param1 = instance;
```suggestion
    command.params.maybe_param1 = static_cast<float>(instance);
```

2023-02-01 12:08 UTC, JonasVautherin commented on src/mavsdk/plugins/winch/winch_impl.cpp
> +    command.params.maybe_param1 = instance;
```suggestion
    command.params.maybe_param1 = static_cast<float>(instance);
```

2023-02-01 12:09 UTC, JonasVautherin commented on src/mavsdk/plugins/winch/winch_impl.cpp
> +    command.params.maybe_param1 = instance;
```suggestion
    command.params.maybe_param1 = static_cast<float>(instance);
```

2023-02-01 12:09 UTC, JonasVautherin commented on src/mavsdk/plugins/winch/winch_impl.cpp
> +    command.params.maybe_param1 = instance;
```suggestion
    command.params.maybe_param1 = static_cast<float>(instance);
```

2023-02-01 12:09 UTC, JonasVautherin commented on src/mavsdk/plugins/winch/winch_impl.cpp
> +    command.params.maybe_param1 = instance;
```suggestion
    command.params.maybe_param1 = static_cast<float>(instance);
```

2023-02-01 12:10 UTC, JonasVautherin commented on src/mavsdk/plugins/winch/winch_impl.cpp
> +    command.params.maybe_param1 = instance;
```suggestion
    command.params.maybe_param1 = static_cast<float>(instance);
```

2023-02-01 13:46 UTC, JonasVautherin requested changes
I could have anticipated the same problem in `gripper_impl.cpp` :see_no_evil:

2023-02-01 13:46 UTC, JonasVautherin commented on src/mavsdk/plugins/gripper/gripper_impl.cpp
> +    command.params.maybe_param1 = instance;
```suggestion
    command.params.maybe_param1 = static_cast<float>(instance);
```

2023-02-01 13:46 UTC, JonasVautherin commented on src/mavsdk/plugins/gripper/gripper_impl.cpp
> +    command.params.maybe_param1 = instance;
```suggestion
    command.params.maybe_param1 = static_cast<float>(instance);
```

2023-02-01 14:24 UTC, merged