add telemetry set_rate_sys_status()
mavlink/MAVSDK pull request #1998
Opened 2023-03-08 14:32 UTC by 41Mo

This pr implements the set_rate_sys_status() function and changes the message sent by the set_rate_battery() function to MSG_ID_BATTERY. 

Previously, the MSG_ID_SYS_STATUS rate was set using the set_rate_battery() function, which can be misleading, this was described in issue #1996.

2023-03-08 22:17 UTC, julianoes requested changes

2023-03-08 22:17 UTC, julianoes commented on src/mavsdk/plugins/telemetry/include/plugins/telemetry/telemetry.h
> +
Note that this API is generated automatically from https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/telemetry/telemetry.proto so the change needs to happen there first.

Sorry, I should have shared this earlier:
https://mavsdk.mavlink.io/main/en/cpp/contributing/plugins.html#add-api-to-proto

2023-06-02 18:37 UTC, ykhedar commented on src/mavsdk/plugins/telemetry/telemetry_impl.cpp
> +        _parent->set_msg_rate(MAVLINK_MSG_ID_BATTERY_STATUS, rate_hz));
This message change was recently merged into main via PR https://github.com/mavlink/MAVSDK/pull/2021 . Maybe rebase current PR and attempt to merge again?

2023-12-18 21:19 UTC, julianoes commented
I'm sorry I didn't act on this earlier. Sometimes life takes over.

Anyway, it looks like the battery rate has been fixed by https://github.com/mavlink/MAVSDK/pull/2021 and I doubt we need health information faster than 1 Hz. I believe PX4 won't send it out quicker anyway as the pre-flight checks don't run faster than 1 Hz anyway.

 If I'm wrong with that let me know.

2023-12-18 21:19 UTC, closed without merging