Add camera client sample code for camera server example
mavlink/MAVSDK pull request #2042
Opened 2023-05-19 16:02 UTC by tbago

* Add camera client sample for camera server example;
    * Remove global using namespace int camera_server.cpp;
    * Remove useless include header in camera_server.cpp;

2023-05-20 02:45 UTC, julianoes requested changes
Thanks for that! See 2 comments inline.

2023-05-20 02:45 UTC, julianoes commented on examples/camera_server/camera_client.cpp
> +    }
We should probably just take one photo and then exit.

2023-05-20 02:45 UTC, julianoes commented on examples/camera_server/camera_server.cpp
> +    auto result = mavsdk.add_any_connection("udp://127.0.0.1:14030");
I think that's correct. Thanks! 

Can you please remove the comment above it though?

2023-05-20 20:55 UTC, julianoes approved these changes

2023-05-21 15:26 UTC, JonasVautherin approved these changes

2023-05-21 15:26 UTC, merged