Added new code for MAV_CMD_DO_SET_SERVO ArduPilot
mavlink/MAVSDK pull request #2113
Opened 2023-08-12 04:23 UTC by trolledbypro

Pull request in support of https://github.com/mavlink/MAVSDK/issues/2111
I added support for actuator control in ArduPilot by modifying the set_actuator function from the Action plugin. I added an if statement that uses the MAV_CMD_DO_SET_SERVO command on ArduPilot systems due to the MAV_CMD_DO_SET_ACTUATOR command not being implemented in ArduPilot. PX4 will continue to use MAV_CMD_DO_SET_ACTUATOR as before.

A word on MAV_CMD_DO_SET_ACTUATOR: this command is capable of setting multiple actuator values at once, while MAV_CMD_DO_SET_SERVO only sets one actuator at a time. Since the set_actuator function is only setting one actuator at a time, MAV_CMD_DO_SET_SERVO is a one-to-one substitute of MAV_CMD_DO_SET_ACTUATOR.

2023-08-13 23:15 UTC, julianoes submitted a review, later dismissed
Thanks!

2023-08-14 13:01 UTC, JonasVautherin requested changes
* Would you mind fixing the style, with `./tools/fix_style.sh .` from the root of the repo?
* The musl CI errors are unrelated (that's a timeout, just ignore it).
* There seems to be a Werror in windows, that should be fixed as well: `warning C4244: '=': conversion from 'const int' to 'float', possible loss of data`. I guess that's your line 524?

```
command.params.maybe_param1 = index;
```

2023-08-14 22:45 UTC, trolledbypro commented
I ran ./tools/fix_style.sh as per [these instructions](https://mavsdk.mavlink.io/main/en/cpp/guide/code_style.html#formatting-and-white-space) and performed the required cast to eliminate the warning

2023-08-15 08:24 UTC, JonasVautherin approved these changes
Thanks a lot! :rocket:

2023-08-15 10:06 UTC, merged