Updated example to use non deprecated code
mavlink/MAVSDK pull request #2258
Opened 2024-03-26 23:15 UTC by takamasanumuro

The smart battery example was not working as it depended on code sections of that were deprecated.
The example was updated to use the new available methods and constructors.

2024-03-26 23:57 UTC, JonasVautherin approved these changes

2024-03-26 23:57 UTC, JonasVautherin commented on examples/battery/battery.cpp
> +    //Subscribe to armed status messages.
```suggestion
    // Subscribe to armed status messages.
```

2024-03-27 04:26 UTC, julianoes requested changes
I'm confused. This is now reverted to the old version.

2024-03-27 14:37 UTC, takamasanumuro commented
Original code is not even compiling, it depends on methods which are no longer available.

2024-03-27 18:40 UTC, julianoes commented
You have it backwards. Which MAVSDK version are you compiling against? What have you installed?

2024-03-27 22:26 UTC, takamasanumuro commented
It seems I had an old version installed on my system. Sorry. I will close this PR. Thanks.

2024-03-27 22:26 UTC, closed without merging

2024-03-28 00:48 UTC, julianoes commented
Ok that makes sense, no worries!