Update UDP client connection syntax to use udpin://
mavlink/MAVSDK pull request #2380
Opened 2024-08-19 15:48 UTC by KarthiAru

Changed all instances of the deprecated UDP client connection syntax udp://:PORT to the recommended udpin://:PORT following the deprecation warning: Connection using udp:// is deprecated, please use udpin:// or udpout:// (cli_arg.cpp:28)

2024-08-19 15:54 UTC, KarthiAru commented
I haven't included the udpout:// related changes in this PR. Will raise a new PR after testing.

2024-08-20 01:28 UTC, julianoes requested changes
Thanks for that! Note that it should be `udpin://0.0.0.0:14540` though, with the new syntax.

2024-08-20 03:52 UTC, KarthiAru commented
Done. Updated to include 0.0.0.0

2024-08-20 11:05 UTC, JonasVautherin approved these changes
🚀

2024-08-20 21:38 UTC, julianoes approved these changes

2024-08-20 21:39 UTC, merged